# Generated by Django 5.2.6 on 2025-10-26 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='test_vry', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crops',
            name='lightLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plants.light'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plants.seasons'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='soilType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plants.soil'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='waterLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plants.water'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MyCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted', models.DateField()),
                ('lastWatered', models.DateField()),
                ('need_watering', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mature', models.BooleanField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCrop', to='plants.crops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCrops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
